#!/bin/sh

mpc next 

ARTIST=$(mpc current -f %artist%)
TRACK=$(mpc current -f %title%)

messageBody=$(printf "%s - %s" "$ARTIST" "$TRACK")

notify-send -t 1000 -i /D/Downloads/next.png "Playing Next Song" "$messageBody"
